#ifndef EZ_ERROR_H_
#define EZ_ERROR_H_


typedef enum E_EZ_ERROR
{
  EZ_FATAL = -1,
  EZ_OK = 0,
  EZ_ERR,
  EZ_ERR_SOCKET_INIT,
  EZ_ERR_SOCKET_DEINIT,
  EZ_ERR_SOCKET_SOCKET,
  EZ_ERR_SOCKET_CREATE,
  EZ_ERR_SOCKET_BIND,
  EZ_ERR_SOCKET_LISTEN,
  EZ_ERR_SOCKET_ACCEPT,
  EZ_ERR_SOCKET_CONNECT,
  EZ_ERR_SOCKET_WRITE,
  EZ_ERR_SOCKET_READ,
  EZ_ERR_SOCKET_DESTROY,
  EZ_ERR_SOCKET_CLOSE,
  EZ_ERR_THREAD_CREATE,
  EZ_ERR_THREAD_JOIN,
  EZ_ERR_THREAD_MUTEX,
  EZ_ERR_THREAD_SEM,
  EZ_ERR_SOCKET_PACKET_SEND,
  EZ_ERR_SOCKET_PACKET_RECEIVE,
  EZ_ERR_SOCKET_PACKET_STX,
  EZ_ERR_SOCKET_PACKET_HEADER,
  EZ_ERR_NOT_CONNECTED,
  EZ_ERR_NOT_BUFFER_FULL,
  EZ_ERR_NOT_BUFFER_EMPTY,
  EZ_ERR_PACKET,
  EZ_ERR_ALIVE,
} ez_err_t;


#endif